# Generated by Django 4.2.25 on 2026-09-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_legacy_item_fields'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='handy_form_upload',
            field=models.FileField(blank=True, null=True, upload_to='po_handy_forms/'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Manual', 'Manual')], default='Digital', max_length=16),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product_description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='products.product'),
        ),
    ]
