# Generated by Django 4.2.25 on 2026-09-28 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_orders', '0003_purchaseorderline_rate_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('dispatch_auto', 'Dispatch (automatic)'), ('import', 'Import')], max_length=16)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_status_changes', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_orders_purchaseorderstatuschange',
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
