# Generated by Django 4.2.25 on 2026-09-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_auththrottle',
            },
        ),
        migrations.AddField(
            model_name='loginrequest',
            name='otp_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loginrequest',
            name='verbal_otp',
            field=models.CharField(blank=True, help_text='Legacy plaintext column; no longer written. Only otp_hash is stored.', max_length=16),
        ),
    ]
