# Generated by Django 4.2.25 on 2026-10-01 07:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_brand_master'),
        ('products', '0002_product_legacy_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(max_length=120)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired')], default='Draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_lists_pricelist',
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taka_length_meters', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price_basis', models.CharField(choices=[('Per Meter', 'Per Meter'), ('Per Taka', 'Per Taka')], max_length=16)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_per_meter', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('price_per_taka', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('taka_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='price_lists.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_entries', to='products.product')),
            ],
            options={
                'db_table': 'price_lists_pricelistentry',
                'ordering': ['product__product_code', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelistentry',
            constraint=models.UniqueConstraint(fields=('price_list', 'product'), name='price_list_product_unique'),
        ),
    ]
