# Generated by Django 4.2.25 on 2026-09-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('entities', '0001_entity_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Upcoming Due', 'Upcoming Due'), ('Due Today', 'Due Today'), ('Overdue', 'Overdue'), ('Payment Confirmation', 'Payment Confirmation'), ('PO Notification', 'PO Notification'), ('Dispatch Notification', 'Dispatch Notification'), ('Admin Access Request', 'Admin Access Request')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reference_type', models.CharField(choices=[('Invoice', 'Invoice'), ('PurchaseOrder', 'PurchaseOrder'), ('Dispatch', 'Dispatch'), ('Payment', 'Payment'), ('AdminAccessRequest', 'AdminAccessRequest')], max_length=24)),
                ('reference_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Dismissed', 'Dismissed')], default='Unread', max_length=16)),
                ('channel', models.CharField(choices=[('In-App', 'In-App'), ('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], default='In-App', max_length=16)),
                ('delivery_status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('Not Applicable', 'Not Applicable')], default='Sent', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customers.customer')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='entities.entity')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['notification_type', 'reference_type', 'reference_id', 'created_at'], name='notif_type_ref_created_idx'), models.Index(fields=['status', 'created_at'], name='notif_status_created_idx')],
            },
        ),
    ]
