# Generated by Django 4.2.25 on 2026-09-16 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_brand_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=40, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('design', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(blank=True, max_length=80)),
                ('quality', models.CharField(blank=True, max_length=80)),
                ('width_size', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(choices=[('Meter', 'Meter'), ('Piece', 'Piece'), ('Kg', 'Kg'), ('Taka', 'Taka'), ('Roll', 'Roll')], default='Meter', max_length=16)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('season', models.CharField(blank=True, max_length=80)),
                ('collection', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Discontinued', 'Discontinued')], default='In Stock', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(help_text='Must be a subcategory (Category with a parent).', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['product_code'],
            },
        ),
    ]
