# Generated by Django 4.2.25 on 2026-09-16 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_entity_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Distributor', 'Distributor')], default='Company', max_length=40)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(blank=True, default='India', max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('zone', models.CharField(blank=True, max_length=80)),
                ('std_code', models.CharField(blank=True, max_length=12)),
                ('pan_no', models.CharField(blank=True, max_length=16)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('vat_tin', models.CharField(blank=True, max_length=20)),
                ('cst_tin', models.CharField(blank=True, max_length=20)),
                ('licence_no', models.CharField(blank=True, max_length=40)),
                ('ecc', models.CharField(blank=True, max_length=40)),
                ('division', models.CharField(blank=True, max_length=80)),
                ('range', models.CharField(blank=True, max_length=80)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lower_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salesman_ref', models.CharField(blank=True, help_text='Placeholder until Salesman master exists.', max_length=120)),
                ('broker_ref', models.CharField(blank=True, help_text='Placeholder until Broker FK is wired.', max_length=120)),
                ('commission_type', models.CharField(blank=True, max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=160)),
                ('rtgs_details', models.CharField(blank=True, max_length=255)),
                ('tds_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tds_form_no', models.CharField(blank=True, max_length=40)),
                ('vat_date', models.DateField(blank=True, null=True)),
                ('vat_date_1', models.DateField(blank=True, null=True)),
                ('comp_id', models.CharField(blank=True, max_length=40)),
                ('visit_day', models.CharField(blank=True, max_length=40)),
                ('file_no', models.CharField(blank=True, max_length=40)),
                ('mill_code', models.CharField(blank=True, max_length=40)),
                ('transport', models.CharField(blank=True, max_length=120)),
                ('other_1', models.CharField(blank=True, max_length=255)),
                ('other_2', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_customer',
                'ordering': ['customer_code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_entity', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='customers.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_links', to='entities.entity')),
            ],
            options={
                'db_table': 'customers_customer_entity',
                'ordering': ['-primary_entity', 'id'],
                'unique_together': {('customer', 'entity')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='entities',
            field=models.ManyToManyField(related_name='customers', through='customers.CustomerEntity', to='entities.entity'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('customer_code', ''), _negated=True), name='customers_customer_code_not_blank'),
        ),
    ]
