# Generated by Django 4.2.25 on 2026-09-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('group', models.CharField(choices=[('Sundry Debtors', 'Sundry Debtors'), ('Sundry Creditors', 'Sundry Creditors'), ('Bank Accounts', 'Bank Accounts'), ('Cash-in-Hand', 'Cash-in-Hand'), ('Income', 'Income'), ('Expense', 'Expense'), ('Capital', 'Capital')], max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('pan', models.CharField(blank=True, max_length=16)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('broker', models.CharField(blank=True, max_length=120)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_type', models.CharField(default='Dr', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_accountmaster',
            },
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('hsn_chapter', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_groupproduct',
            },
        ),
        migrations.CreateModel(
            name='MasterBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=80)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_head_office', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_masterbranch',
            },
        ),
        migrations.CreateModel(
            name='MstFinYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'masters_mstfinyear',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_parameter',
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('construction', models.CharField(blank=True, max_length=80)),
                ('width_inches', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hsn', models.CharField(max_length=12)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('packing_unit', models.CharField(default='Meters', max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.groupproduct')),
            ],
            options={
                'db_table': 'masters_itemmaster',
            },
        ),
    ]
