# Generated by Django 4.2.25 on 2026-09-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('firm_name', models.CharField(blank=True, max_length=200)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pan', models.CharField(blank=True, max_length=16)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_brokermaster',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hsn_coverage', models.CharField(blank=True, max_length=255)),
                ('statutory_notification', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('rcm_applicable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'masters_taxslab',
                'ordering': ['gst_percent', 'code'],
            },
        ),
        migrations.AddField(
            model_name='accountmaster',
            name='linked_branches',
            field=models.ManyToManyField(blank=True, related_name='party_accounts', to='masters.masterbranch'),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='avg_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='construction',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='gsm_range',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='mill_origin',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='parameter',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='masters.groupproduct'),
        ),
        migrations.CreateModel(
            name='ChartAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=20)),
                ('nature', models.CharField(default='Debit', max_length=10)),
                ('is_group', models.BooleanField(default=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.chartaccount')),
            ],
            options={
                'db_table': 'masters_chartaccount',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='accountmaster',
            name='broker_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='masters.brokermaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='tax_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='masters.taxslab'),
        ),
    ]
