from django.urls import path

from . import views

urlpatterns = [
    path("api/auth/health", views.health),
    path("api/auth/health/", views.health),
    path("api/check-credentials", views.check_credentials),
    path("api/check-credentials/", views.check_credentials),
    path("api/auth/check-credentials", views.check_credentials),
    path("api/admin-login", views.admin_login),
    path("api/admin-login/", views.admin_login),
    path("api/admin/verify-pin", views.admin_login),
    path("api/admin/verify-pin/", views.admin_login),
    path("api/auth/admin/login", views.admin_login),
    path("api/auth/admin/verify-pin", views.admin_login),
    path("api/admin/pin-status", views.pin_status),
    path("api/auth/admin/pin-status", views.pin_status),
    path("api/login", views.operator_login_request),
    path("api/login/", views.operator_login_request),
    path("api/auth/operator/request", views.operator_login_request),
    path("api/check-request-status", views.check_request_status),
    path("api/check-request-status/", views.check_request_status),
    path("api/auth/operator/status", views.check_request_status),
    path("api/auth/admin/queue", views.admin_queue),
    path("api/admin/approve/<str:request_id>", views.approve_request),
    path("api/admin/approve/<str:request_id>/", views.approve_request),
    path("api/auth/admin/approve/<str:request_id>/", views.approve_request),
    path("api/admin/reject/<str:request_id>", views.reject_request),
    path("api/admin/reject/<str:request_id>/", views.reject_request),
    path("verify-otp/", views.verify_otp),
    path("api/verify-otp", views.verify_otp),
    path("api/verify-otp/", views.verify_otp),
    path("api/auth/operator/verify-otp", views.verify_otp),
    path("api/auth/admin/pin-reset/request", views.pin_reset_request),
    path("api/auth/admin/pin-reset/confirm", views.pin_reset_confirm),
    path("api/auth/me", views.session_me),
    path("api/auth/me/", views.session_me),
    path("api/auth/logout", views.logout_view),
    path("api/auth/audit-trail", views.audit_trail),
    path("api/dashboard/summary/", views.dashboard_summary),
]
