# Generated by Django 4.2.25 on 2026-09-16 10:07

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('entities', '0001_entity_master'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=40, unique=True)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('customer_code', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('Other', 'Other')], max_length=24)),
                ('bank_cash_account', models.CharField(max_length=120)),
                ('transaction_reference', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='entities.entity')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='invoices.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_paymentallocation',
                'ordering': ['id'],
            },
        ),
    ]
