# Generated by Django 4.2.25 on 2026-09-16 09:51

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_entity_master'),
        ('customers', '0001_initial'),
        ('products', '0002_product_legacy_item_fields'),
        ('purchase_orders', '0002_purchaseorder_handy_form_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_brand_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('customer_code', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Adjusted', 'Adjusted')], default='Draft', max_length=24)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_terms', models.CharField(blank=True, max_length=160)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='entities.entity')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'invoices_invoice',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(blank=True, max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='products.product')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='purchase_orders.purchaseorderline')),
            ],
            options={
                'db_table': 'invoices_invoiceline',
                'ordering': ['id'],
            },
        ),
    ]
