# Generated by Django 4.2.25 on 2026-09-16 09:37

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_orders', '0002_purchaseorder_handy_form_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(default=datetime.date.today)),
                ('lr_number', models.CharField(max_length=80)),
                ('transporter', models.CharField(max_length=160)),
                ('challan_reference', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'dispatches_dispatch',
                'ordering': ['-dispatch_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dispatches.dispatch')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_lines', to='purchase_orders.purchaseorderline')),
            ],
            options={
                'db_table': 'dispatches_dispatchline',
                'ordering': ['id'],
            },
        ),
    ]
