# Generated by Django 4.2.25 on 2026-09-16 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('entity_name', models.CharField(max_length=200, unique=True)),
                ('entity_type', models.CharField(choices=[('Head Office', 'Head Office'), ('Regional', 'Regional'), ('Branch', 'Branch')], default='Branch', max_length=40)),
                ('cash_code', models.CharField(blank=True, max_length=40)),
                ('invoice_series', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, default='India', max_length=80)),
                ('pin_code', models.CharField(blank=True, max_length=12)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('zone', models.CharField(blank=True, max_length=80)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('std_code', models.CharField(blank=True, max_length=12)),
                ('pan_no', models.CharField(blank=True, max_length=16)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('cst_tin', models.CharField(blank=True, max_length=20)),
                ('licence_no', models.CharField(blank=True, max_length=40)),
                ('ecc', models.CharField(blank=True, max_length=40)),
                ('division', models.CharField(blank=True, max_length=80)),
                ('range', models.CharField(blank=True, max_length=80)),
                ('other_1', models.CharField(blank=True, max_length=255)),
                ('other_2', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
                ('parent_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_entities', to='entities.entity')),
            ],
            options={
                'db_table': 'entities_entity',
                'ordering': ['short_code'],
            },
        ),
    ]
