# Generated by Django 4.2.25 on 2026-09-16 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(max_length=20, unique=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_no', models.CharField(blank=True, max_length=20)),
                ('pan_no', models.CharField(blank=True, max_length=16)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commission_basis', models.CharField(blank=True, choices=[('% of invoice value', '% of invoice value'), ('% of quantity', '% of quantity'), ('Fixed per order', 'Fixed per order')], default='% of invoice value', max_length=40)),
                ('payment_terms', models.TextField(blank=True)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('order_method', models.CharField(choices=[('Digital PO', 'Digital PO'), ('Manual/POR', 'Manual/POR')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brands_brand',
                'ordering': ['brand_code'],
            },
        ),
    ]
