# Generated by Django 4.2.25 on 2026-09-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
            ],
            options={
                'db_table': 'transactions_journalentry',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('meters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('eway_bill', models.CharField(blank=True, max_length=30)),
                ('vehicle_no', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.masterbranch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.itemmaster')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_salesinvoice',
            },
        ),
        migrations.CreateModel(
            name='PaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_no', models.CharField(max_length=30, unique=True)),
                ('adjustment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_paymentadjustment',
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('meters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('broker', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='booked', max_length=30)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.masterbranch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.itemmaster')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_orderform',
            },
        ),
        migrations.CreateModel(
            name='MaterialReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=30, unique=True)),
                ('return_date', models.DateField()),
                ('meters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.itemmaster')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_returns', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_materialreturned',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.accountmaster')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.journalentry')),
            ],
            options={
                'db_table': 'transactions_journalline',
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(max_length=30, unique=True)),
                ('note_date', models.DateField()),
                ('original_bill_no', models.CharField(blank=True, max_length=30)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_debitnote',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(max_length=30, unique=True)),
                ('note_date', models.DateField()),
                ('original_invoice_no', models.CharField(blank=True, max_length=30)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_creditnote',
            },
        ),
        migrations.CreateModel(
            name='CashReceivedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_cashreceivedvoucher',
            },
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_cashpayment',
            },
        ),
        migrations.CreateModel(
            name='BankReceivedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cheque_no', models.CharField(blank=True, max_length=40)),
                ('drawn_on', models.CharField(blank=True, max_length=120)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='cleared', max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_receipts_as_bank', to='masters.accountmaster')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_receipts', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_bankreceivedvoucher',
            },
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_payments_as_bank', to='masters.accountmaster')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_payments', to='masters.accountmaster')),
            ],
            options={
                'db_table': 'transactions_bankpayment',
            },
        ),
    ]
